# minimal when using setup.cfg

Minimum requirements to build package in venv w/ setuptools 
requires = [
    "setuptools",
    "wheel",]


#[build-system]
#requires = [
#   "setuptools",
#    "wheel",
#    "robo-base",]
